INSERT INTO Country (isoCode, name) VALUES ('ABW','Aruba');
INSERT INTO Country (isoCode, name) VALUES ('AFG','Afghanistan');
INSERT INTO Country (isoCode, name) VALUES ('AGO','Angola');
INSERT INTO Country (isoCode, name) VALUES ('AIA','Anguilla');
INSERT INTO Country (isoCode, name) VALUES ('ALA','Îles Åland');
INSERT INTO Country (isoCode, name) VALUES ('ALB','Albanie');
INSERT INTO Country (isoCode, name) VALUES ('AND','Andorre');
INSERT INTO Country (isoCode, name) VALUES ('ANT','Antilles Néerlandaises');
INSERT INTO Country (isoCode, name) VALUES ('ARE','Émirats Arabes Unis');
INSERT INTO Country (isoCode, name) VALUES ('ARG','Argentine');
INSERT INTO Country (isoCode, name) VALUES ('ARM','Arménie');
INSERT INTO Country (isoCode, name) VALUES ('ASM','Samoa Américaines');
INSERT INTO Country (isoCode, name) VALUES ('ATA','Antarctique');
INSERT INTO Country (isoCode, name) VALUES ('ATF','Terres Australes Françaises');
INSERT INTO Country (isoCode, name) VALUES ('ATG','Antigua-et-Barbuda');
INSERT INTO Country (isoCode, name) VALUES ('AUS','Australie');
INSERT INTO Country (isoCode, name) VALUES ('AUT','Autriche');
INSERT INTO Country (isoCode, name) VALUES ('AZE','Azerbaïdjan');
INSERT INTO Country (isoCode, name) VALUES ('BDI','Burundi');
INSERT INTO Country (isoCode, name) VALUES ('BEL','Belgique');
INSERT INTO Country (isoCode, name) VALUES ('BEN','Bénin');
INSERT INTO Country (isoCode, name) VALUES ('BFA','Burkina Faso');
INSERT INTO Country (isoCode, name) VALUES ('BGD','Bangladesh');
INSERT INTO Country (isoCode, name) VALUES ('BGR','Bulgarie');
INSERT INTO Country (isoCode, name) VALUES ('BHR','Bahreïn');
INSERT INTO Country (isoCode, name) VALUES ('BHS','Bahamas');
INSERT INTO Country (isoCode, name) VALUES ('BIH','Bosnie-Herzégovine');
INSERT INTO Country (isoCode, name) VALUES ('BLR','Bélarus');
INSERT INTO Country (isoCode, name) VALUES ('BLZ','Belize');
INSERT INTO Country (isoCode, name) VALUES ('BMU','Bermudes');
INSERT INTO Country (isoCode, name) VALUES ('BOL','Bolivie');
INSERT INTO Country (isoCode, name) VALUES ('BRA','Brésil');
INSERT INTO Country (isoCode, name) VALUES ('BRB','Barbade');
INSERT INTO Country (isoCode, name) VALUES ('BRN','Brunéi Darussalam');
INSERT INTO Country (isoCode, name) VALUES ('BTN','Bhoutan');
INSERT INTO Country (isoCode, name) VALUES ('BVT','Île Bouvet');
INSERT INTO Country (isoCode, name) VALUES ('BWA','Botswana');
INSERT INTO Country (isoCode, name) VALUES ('CAF','République Centrafricaine');
INSERT INTO Country (isoCode, name) VALUES ('CAN','Canada');
INSERT INTO Country (isoCode, name) VALUES ('CCK','Îles Cocos (Keeling)');
INSERT INTO Country (isoCode, name) VALUES ('CHE','Suisse');
INSERT INTO Country (isoCode, name) VALUES ('CHL','Chili');
INSERT INTO Country (isoCode, name) VALUES ('CHN','Chine');
INSERT INTO Country (isoCode, name) VALUES ('CIV','Côte d''Ivoire');
INSERT INTO Country (isoCode, name) VALUES ('CMR','Cameroun');
INSERT INTO Country (isoCode, name) VALUES ('COD','République Démocratique du Congo');
INSERT INTO Country (isoCode, name) VALUES ('COG','République du Congo');
INSERT INTO Country (isoCode, name) VALUES ('COK','Îles Cook');
INSERT INTO Country (isoCode, name) VALUES ('COL','Colombie');
INSERT INTO Country (isoCode, name) VALUES ('COM','Comores');
INSERT INTO Country (isoCode, name) VALUES ('CPV','Cap-vert');
INSERT INTO Country (isoCode, name) VALUES ('CRI','Costa Rica');
INSERT INTO Country (isoCode, name) VALUES ('CUB','Cuba');
INSERT INTO Country (isoCode, name) VALUES ('CXR','Île Christmas');
INSERT INTO Country (isoCode, name) VALUES ('CYM','Îles Caïmanes');
INSERT INTO Country (isoCode, name) VALUES ('CYP','Chypre');
INSERT INTO Country (isoCode, name) VALUES ('CZE','République Tchèque');
INSERT INTO Country (isoCode, name) VALUES ('DEU','Allemagne');
INSERT INTO Country (isoCode, name) VALUES ('DJI','Djibouti');
INSERT INTO Country (isoCode, name) VALUES ('DMA','Dominique');
INSERT INTO Country (isoCode, name) VALUES ('DNK','Danemark');
INSERT INTO Country (isoCode, name) VALUES ('DOM','République Dominicaine');
INSERT INTO Country (isoCode, name) VALUES ('DZA','Algérie');
INSERT INTO Country (isoCode, name) VALUES ('ECU','Équateur');
INSERT INTO Country (isoCode, name) VALUES ('EGY','Égypte');
INSERT INTO Country (isoCode, name) VALUES ('ERI','Érythrée');
INSERT INTO Country (isoCode, name) VALUES ('ESH','Sahara Occidental');
INSERT INTO Country (isoCode, name) VALUES ('ESP','Espagne');
INSERT INTO Country (isoCode, name) VALUES ('EST','Estonie');
INSERT INTO Country (isoCode, name) VALUES ('ETH','Éthiopie');
INSERT INTO Country (isoCode, name) VALUES ('FIN','Finlande');
INSERT INTO Country (isoCode, name) VALUES ('FJI','Fidji');
INSERT INTO Country (isoCode, name) VALUES ('FLK','Îles (malvinas) Falkland');
INSERT INTO Country (isoCode, name) VALUES ('FRA','France');
INSERT INTO Country (isoCode, name) VALUES ('FRO','Îles Féroé');
INSERT INTO Country (isoCode, name) VALUES ('FSM','États Fédérés de Micronésie');
INSERT INTO Country (isoCode, name) VALUES ('GAB','Gabon');
INSERT INTO Country (isoCode, name) VALUES ('GBR','Royaume-Uni');
INSERT INTO Country (isoCode, name) VALUES ('GEO','Géorgie');
INSERT INTO Country (isoCode, name) VALUES ('GHA','Ghana');
INSERT INTO Country (isoCode, name) VALUES ('GIB','Gibraltar');
INSERT INTO Country (isoCode, name) VALUES ('GIN','Guinée');
INSERT INTO Country (isoCode, name) VALUES ('GLP','Guadeloupe');
INSERT INTO Country (isoCode, name) VALUES ('GMB','Gambie');
INSERT INTO Country (isoCode, name) VALUES ('GNB','Guinée-Bissau');
INSERT INTO Country (isoCode, name) VALUES ('GNQ','Guinée Équatoriale');
INSERT INTO Country (isoCode, name) VALUES ('GRC','Grèce');
INSERT INTO Country (isoCode, name) VALUES ('GRD','Grenade');
INSERT INTO Country (isoCode, name) VALUES ('GRL','Groenland');
INSERT INTO Country (isoCode, name) VALUES ('GTM','Guatemala');
INSERT INTO Country (isoCode, name) VALUES ('GUF','Guyane Française');
INSERT INTO Country (isoCode, name) VALUES ('GUM','Guam');
INSERT INTO Country (isoCode, name) VALUES ('GUY','Guyana');
INSERT INTO Country (isoCode, name) VALUES ('HKG','Hong-Kong');
INSERT INTO Country (isoCode, name) VALUES ('HMD','Îles Heard et Mcdonald');
INSERT INTO Country (isoCode, name) VALUES ('HND','Honduras');
INSERT INTO Country (isoCode, name) VALUES ('HRV','Croatie');
INSERT INTO Country (isoCode, name) VALUES ('HTI','Haïti');
INSERT INTO Country (isoCode, name) VALUES ('HUN','Hongrie');
INSERT INTO Country (isoCode, name) VALUES ('IDN','Indonésie');
INSERT INTO Country (isoCode, name) VALUES ('IMN','Île de Man');
INSERT INTO Country (isoCode, name) VALUES ('IND','Inde');
INSERT INTO Country (isoCode, name) VALUES ('IOT','Territoire Britannique de l''Océan Indien');
INSERT INTO Country (isoCode, name) VALUES ('IRL','Irlande');
INSERT INTO Country (isoCode, name) VALUES ('IRN','République Islamique d''Iran');
INSERT INTO Country (isoCode, name) VALUES ('IRQ','Iraq');
INSERT INTO Country (isoCode, name) VALUES ('ISL','Islande');
INSERT INTO Country (isoCode, name) VALUES ('ISR','Israël');
INSERT INTO Country (isoCode, name) VALUES ('ITA','Italie');
INSERT INTO Country (isoCode, name) VALUES ('JAM','Jamaïque');
INSERT INTO Country (isoCode, name) VALUES ('JOR','Jordanie');
INSERT INTO Country (isoCode, name) VALUES ('JPN','Japon');
INSERT INTO Country (isoCode, name) VALUES ('KAZ','Kazakhstan');
INSERT INTO Country (isoCode, name) VALUES ('KEN','Kenya');
INSERT INTO Country (isoCode, name) VALUES ('KGZ','Kirghizistan');
INSERT INTO Country (isoCode, name) VALUES ('KHM','Cambodge');
INSERT INTO Country (isoCode, name) VALUES ('KIR','Kiribati');
INSERT INTO Country (isoCode, name) VALUES ('KNA','Saint-Kitts-et-Nevis');
INSERT INTO Country (isoCode, name) VALUES ('KOR','République de Corée');
INSERT INTO Country (isoCode, name) VALUES ('KWT','Koweït');
INSERT INTO Country (isoCode, name) VALUES ('LAO','République Démocratique Populaire Lao');
INSERT INTO Country (isoCode, name) VALUES ('LBN','Liban');
INSERT INTO Country (isoCode, name) VALUES ('LBR','Libéria');
INSERT INTO Country (isoCode, name) VALUES ('LBY','Jamahiriya Arabe Libyenne');
INSERT INTO Country (isoCode, name) VALUES ('LCA','Sainte-Lucie');
INSERT INTO Country (isoCode, name) VALUES ('LIE','Liechtenstein');
INSERT INTO Country (isoCode, name) VALUES ('LKA','Sri Lanka');
INSERT INTO Country (isoCode, name) VALUES ('LSO','Lesotho');
INSERT INTO Country (isoCode, name) VALUES ('LTU','Lituanie');
INSERT INTO Country (isoCode, name) VALUES ('LUX','Luxembourg');
INSERT INTO Country (isoCode, name) VALUES ('LVA','Lettonie');
INSERT INTO Country (isoCode, name) VALUES ('MAC','Macao');
INSERT INTO Country (isoCode, name) VALUES ('MAR','Maroc');
INSERT INTO Country (isoCode, name) VALUES ('MCO','Monaco');
INSERT INTO Country (isoCode, name) VALUES ('MDA','République de Moldova');
INSERT INTO Country (isoCode, name) VALUES ('MDG','Madagascar');
INSERT INTO Country (isoCode, name) VALUES ('MDV','Maldives');
INSERT INTO Country (isoCode, name) VALUES ('MEX','Mexique');
INSERT INTO Country (isoCode, name) VALUES ('MHL','Îles Marshall');
INSERT INTO Country (isoCode, name) VALUES ('MKD','L''ex-République Yougoslave de Macédoine');
INSERT INTO Country (isoCode, name) VALUES ('MLI','Mali');
INSERT INTO Country (isoCode, name) VALUES ('MLT','Malte');
INSERT INTO Country (isoCode, name) VALUES ('MMR','Myanmar');
INSERT INTO Country (isoCode, name) VALUES ('MNG','Mongolie');
INSERT INTO Country (isoCode, name) VALUES ('MNP','Îles Mariannes du Nord');
INSERT INTO Country (isoCode, name) VALUES ('MOZ','Mozambique');
INSERT INTO Country (isoCode, name) VALUES ('MRT','Mauritanie');
INSERT INTO Country (isoCode, name) VALUES ('MSR','Montserrat');
INSERT INTO Country (isoCode, name) VALUES ('MTQ','Martinique');
INSERT INTO Country (isoCode, name) VALUES ('MUS','Maurice');
INSERT INTO Country (isoCode, name) VALUES ('MWI','Malawi');
INSERT INTO Country (isoCode, name) VALUES ('MYS','Malaisie');
INSERT INTO Country (isoCode, name) VALUES ('MYT','Mayotte');
INSERT INTO Country (isoCode, name) VALUES ('NAM','Namibie');
INSERT INTO Country (isoCode, name) VALUES ('NCL','Nouvelle-Calédonie');
INSERT INTO Country (isoCode, name) VALUES ('NER','Niger');
INSERT INTO Country (isoCode, name) VALUES ('NFK','Île Norfolk');
INSERT INTO Country (isoCode, name) VALUES ('NGA','Nigéria');
INSERT INTO Country (isoCode, name) VALUES ('NIC','Nicaragua');
INSERT INTO Country (isoCode, name) VALUES ('NIU','Niué');
INSERT INTO Country (isoCode, name) VALUES ('NLD','Country-Bas');
INSERT INTO Country (isoCode, name) VALUES ('NOR','Norvège');
INSERT INTO Country (isoCode, name) VALUES ('NPL','Népal');
INSERT INTO Country (isoCode, name) VALUES ('NRU','Nauru');
INSERT INTO Country (isoCode, name) VALUES ('NZL','Nouvelle-Zélande');
INSERT INTO Country (isoCode, name) VALUES ('OMN','Oman');
INSERT INTO Country (isoCode, name) VALUES ('PAK','Pakistan');
INSERT INTO Country (isoCode, name) VALUES ('PAN','Panama');
INSERT INTO Country (isoCode, name) VALUES ('PCN','Pitcairn');
INSERT INTO Country (isoCode, name) VALUES ('PER','Pérou');
INSERT INTO Country (isoCode, name) VALUES ('PHL','Philippines');
INSERT INTO Country (isoCode, name) VALUES ('PLW','Palaos');
INSERT INTO Country (isoCode, name) VALUES ('PNG','Papouasie-Nouvelle-Guinée');
INSERT INTO Country (isoCode, name) VALUES ('POL','Pologne');
INSERT INTO Country (isoCode, name) VALUES ('PRI','Porto Rico');
INSERT INTO Country (isoCode, name) VALUES ('PRK','République Populaire Démocratique de Corée');
INSERT INTO Country (isoCode, name) VALUES ('PRT','Portugal');
INSERT INTO Country (isoCode, name) VALUES ('PRY','Paraguay');
INSERT INTO Country (isoCode, name) VALUES ('PSE','Territoire Palestinien Occupé');
INSERT INTO Country (isoCode, name) VALUES ('PYF','Polynésie Française');
INSERT INTO Country (isoCode, name) VALUES ('QAT','Qatar');
INSERT INTO Country (isoCode, name) VALUES ('REU','Réunion');
INSERT INTO Country (isoCode, name) VALUES ('ROU','Roumanie');
INSERT INTO Country (isoCode, name) VALUES ('RUS','Fédération de Russie');
INSERT INTO Country (isoCode, name) VALUES ('RWA','Rwanda');
INSERT INTO Country (isoCode, name) VALUES ('SAU','Arabie Saoudite');
INSERT INTO Country (isoCode, name) VALUES ('SCG','Serbie-et-Monténégro');
INSERT INTO Country (isoCode, name) VALUES ('SDN','Soudan');
INSERT INTO Country (isoCode, name) VALUES ('SEN','Sénégal');
INSERT INTO Country (isoCode, name) VALUES ('SGP','Singapour');
INSERT INTO Country (isoCode, name) VALUES ('SGS','Géorgie du Sud et les Îles Sandwich du Sud');
INSERT INTO Country (isoCode, name) VALUES ('SHN','Sainte-Hélène');
INSERT INTO Country (isoCode, name) VALUES ('SJM','Svalbard etÎle Jan Mayen');
INSERT INTO Country (isoCode, name) VALUES ('SLB','Îles Salomon');
INSERT INTO Country (isoCode, name) VALUES ('SLE','Sierra Leone');
INSERT INTO Country (isoCode, name) VALUES ('SLV','El Salvador');
INSERT INTO Country (isoCode, name) VALUES ('SMR','Saint-Marin');
INSERT INTO Country (isoCode, name) VALUES ('SOM','Somalie');
INSERT INTO Country (isoCode, name) VALUES ('SPM','Saint-Pierre-et-Miquelon');
INSERT INTO Country (isoCode, name) VALUES ('STP','Sao Tomé-et-Principe');
INSERT INTO Country (isoCode, name) VALUES ('SUR','Suriname');
INSERT INTO Country (isoCode, name) VALUES ('SVK','Slovaquie');
INSERT INTO Country (isoCode, name) VALUES ('SVN','Slovénie');
INSERT INTO Country (isoCode, name) VALUES ('SWE','Suède');
INSERT INTO Country (isoCode, name) VALUES ('SWZ','Swaziland');
INSERT INTO Country (isoCode, name) VALUES ('SYC','Seychelles');
INSERT INTO Country (isoCode, name) VALUES ('SYR','République Arabe Syrienne');
INSERT INTO Country (isoCode, name) VALUES ('TCA','Îles Turks et Caïques');
INSERT INTO Country (isoCode, name) VALUES ('TCD','Tchad');
INSERT INTO Country (isoCode, name) VALUES ('TGO','Togo');
INSERT INTO Country (isoCode, name) VALUES ('THA','Thaïlande');
INSERT INTO Country (isoCode, name) VALUES ('TJK','Tadjikistan');
INSERT INTO Country (isoCode, name) VALUES ('TKL','Tokelau');
INSERT INTO Country (isoCode, name) VALUES ('TKM','Turkménistan');
INSERT INTO Country (isoCode, name) VALUES ('TLS','Timor-Leste');
INSERT INTO Country (isoCode, name) VALUES ('TON','Tonga');
INSERT INTO Country (isoCode, name) VALUES ('TTO','Trinité-et-Tobago');
INSERT INTO Country (isoCode, name) VALUES ('TUN','Tunisie');
INSERT INTO Country (isoCode, name) VALUES ('TUR','Turquie');
INSERT INTO Country (isoCode, name) VALUES ('TUV','Tuvalu');
INSERT INTO Country (isoCode, name) VALUES ('TWN','Taïwan');
INSERT INTO Country (isoCode, name) VALUES ('TZA','République-Unie de Tanzanie');
INSERT INTO Country (isoCode, name) VALUES ('UGA','Ouganda');
INSERT INTO Country (isoCode, name) VALUES ('UKR','Ukraine');
INSERT INTO Country (isoCode, name) VALUES ('UMI','Îles Mineures Éloignées des États-Unis');
INSERT INTO Country (isoCode, name) VALUES ('URY','Uruguay');
INSERT INTO Country (isoCode, name) VALUES ('USA','États-Unis');
INSERT INTO Country (isoCode, name) VALUES ('UZB','Ouzbékistan');
INSERT INTO Country (isoCode, name) VALUES ('VAT','Saint-Siège (état de la Cité du Vatican)');
INSERT INTO Country (isoCode, name) VALUES ('VCT','Saint-Vincent-et-les Grenadines');
INSERT INTO Country (isoCode, name) VALUES ('VEN','Venezuela');
INSERT INTO Country (isoCode, name) VALUES ('VGB','Îles Vierges Britanniques');
INSERT INTO Country (isoCode, name) VALUES ('VIR','Îles Vierges des États-Unis');
INSERT INTO Country (isoCode, name) VALUES ('VNM','Viet Nam');
INSERT INTO Country (isoCode, name) VALUES ('VUT','Vanuatu');
INSERT INTO Country (isoCode, name) VALUES ('WLF','Wallis et Futuna');
INSERT INTO Country (isoCode, name) VALUES ('WSM','Samoa');
INSERT INTO Country (isoCode, name) VALUES ('YEM','Yémen');
INSERT INTO Country (isoCode, name) VALUES ('ZAF','Afrique du Sud');
INSERT INTO Country (isoCode, name) VALUES ('ZMB','Zambie');
INSERT INTO Country (isoCode, name) VALUES ('ZWE','Zimbabwe');