//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProGestionGSB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoosenCountryYear
    {
        public int country_id { get; set; }
        public int choosenYear { get; set; }
        public Nullable<double> plafond { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
